In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
from sklearn.impute import SimpleImputer

In [70]:
from sklearn.compose import ColumnTransformer

In [71]:
df = pd.read_csv('titanic_toy.csv')

In [72]:
df.info

<bound method DataFrame.info of       Age     Fare  Family  Survived
0    22.0   7.2500       1         0
1    38.0  71.2833       1         1
2    26.0   7.9250       0         1
3    35.0  53.1000       1         1
4    35.0   8.0500       0         0
..    ...      ...     ...       ...
886  27.0  13.0000       0         0
887  19.0  30.0000       0         1
888   NaN  23.4500       3         0
889  26.0      NaN       0         1
890  32.0   7.7500       0         0

[891 rows x 4 columns]>

In [73]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [74]:
df.sample(5)

      Age     Fare  Family  Survived
363  35.0   7.0500       0         0
421  21.0   7.7333       0         0
447  34.0  26.5500       0         1
478  22.0   7.5208       0         0
649  23.0      NaN       0         1

In [75]:
df.tail()

      Age   Fare  Family  Survived
886  27.0  13.00       0         0
887  19.0  30.00       0         1
888   NaN  23.45       3         0
889  26.0    NaN       0         1
890  32.0   7.75       0         0

In [76]:
df.isna().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [77]:
df.isna().mean

<bound method DataFrame.mean of        Age   Fare  Family  Survived
0    False  False   False     False
1    False  False   False     False
2    False  False   False     False
3    False  False   False     False
4    False  False   False     False
..     ...    ...     ...       ...
886  False  False   False     False
887  False  False   False     False
888   True  False   False     False
889  False   True   False     False
890  False  False   False     False

[891 rows x 4 columns]>

In [78]:
X = df.drop(columns=['Survived'])

In [79]:
y = df['Survived']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state= 2)

In [81]:
X_train.shape

(712, 3)

In [82]:
X_test.shape

(179, 3)

In [83]:
X_train.mean()

Age       29.785904
Fare      32.617597
Family     0.932584
dtype: float64

In [84]:
X_train.isna().mean()

Age       0.207865
Fare      0.050562
Family    0.000000
dtype: float64

In [85]:
mean_age = X_train['Age'].mean()
median_age = X_train['Age'].median()

mean_fare = X_train['Fare'].mean()
median_fare = X_train['Fare'].median()

In [86]:
X_train['Age_median'] = X_train['Age'].fillna(median_age)
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)

X_train['Fare_median'] = X_train['Fare'].fillna(median_fare)
X_train['Fare_mean'] = X_train['Fare'].fillna(mean_fare)

In [87]:
X_train.sample(5)

      Age     Fare  Family  Age_median   Age_mean  Fare_median  Fare_mean
867  31.0  50.4958       0       31.00  31.000000      50.4958    50.4958
759  33.0  86.5000       0       33.00  33.000000      86.5000    86.5000
725  20.0   8.6625       0       20.00  20.000000       8.6625     8.6625
863   NaN  69.5500      10       28.75  29.785904      69.5500    69.5500
165   9.0  20.5250       2        9.00   9.000000      20.5250    20.5250

In [88]:
print('Original Age variable variance: ', X_train['Age'].var())
print('Age Variance after median imputation: ', X_train['Age_median'].var())
print('Age Variance after mean imputation: ', X_train['Age_mean'].var())

print('Original Fare variable variance: ', X_train['Fare'].var())
print('Fare Variance after median imputation: ', X_train['Fare_median'].var())
print('Fare Variance after mean imputation: ', X_train['Fare_mean'].var())

Original Age variable variance:  204.3495133904614
Age Variance after median imputation:  161.9895663346054
Age Variance after mean imputation:  161.81262452718673
Original Fare variable variance:  2448.197913706318
Fare Variance after median imputation:  2340.0910219753637
Fare Variance after mean imputation:  2324.2385256705547

In [89]:
X_train.cov()

,Age,Fare,Family,Age_median,Age_mean,Fare_median,Fare_mean
Age,204.349513,70.719262,-6.498901,204.349513,204.349513,64.858859,66.665205
Fare,70.719262,2448.197914,17.258917,57.957599,55.603719,2448.197914,2448.197914
Family,-6.498901,17.258917,2.735252,-5.112563,-5.146106,16.476305,16.385048
Age_median,204.349513,57.957599,-5.112563,161.989566,161.812625,53.553455,55.023037
Age_mean,204.349513,55.603719,-5.146106,161.812625,161.812625,51.358000,52.788341
Fare_median,64.858859,2448.197914,16.476305,53.553455,51.358000,2340.091022,2324.238526
Fare_mean,66.665205,2448.197914,16.385048,55.023037,52.788341,2324.238526,2324.238526

In [90]:
X_train.corr()

,Age,Fare,Family,Age_median,Age_mean,Fare_median,Fare_mean
Age,1.000000,0.092644,-0.299113,1.000000,1.000000,0.087356,0.090156
Fare,0.092644,1.000000,0.208268,0.091757,0.088069,1.000000,1.000000
Family,-0.299113,0.208268,1.000000,-0.242883,-0.244610,0.205942,0.205499
Age_median,1.000000,0.091757,-0.242883,1.000000,0.999454,0.086982,0.089673
Age_mean,1.000000,0.088069,-0.244610,0.999454,1.000000,0.083461,0.086078
Fare_median,0.087356,1.000000,0.205942,0.086982,0.083461,1.000000,0.996607
Fare_mean,0.090156,1.000000,0.205499,0.089673,0.086078,0.996607,1.000000

In [93]:
X_train[['Age', 'Age_median', 'Age_mean']].boxplot()

In [94]:
X_train[['Fare', 'Fare_median', 'Fare_mean']].boxplot()

In [ ]:
# using sklearn

In [95]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [98]:
imputer1 = SimpleImputer(strategy = 'median')
imputer2 = SimpleImputer(strategy = 'mean')

In [99]:
trf = ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare'])
],remainder = 'passthrough')

In [100]:
trf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer1', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('imputer2', SimpleImputer(), ['Fare'])])