In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df.sample(5)

    age  gender  fever   cough       city has_covid
34   74    Male  102.0    Mild     Mumbai       Yes
47   18  Female  104.0    Mild  Bangalore        No
63   10    Male  100.0    Mild  Bangalore        No
43   22  Female   99.0    Mild  Bangalore       Yes
84   69  Female   98.0  Strong     Mumbai        No

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split( df.drop(columns = ['has_covid']) , df['has_covid'] , test_size = 0.2 , random_state= 0)

In [10]:
X_train.shape

(80, 5)

In [11]:
X_train.head()

    age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [19]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [26]:
transformer.fit_transform(X_train).shape

(80, 7)

In [24]:

transformer.transform(X_test).shape

(20, 7)