In [1]:
import numpy as np
import pandas as pd
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [2]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [3]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
#year

In [10]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
623 2018-09-13        4597        3       2       2018
726 2019-10-20        5794        6       1       2019
142 2018-08-06        1610        3       1       2018
222 2019-01-22        5002       13      15       2019
852 2018-09-04        2706        9       8       2018

In [12]:
date['date_month_no'] = date['date'].dt.month

In [13]:
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
422 2019-11-24        6717        3       1       2019             11
192 2019-04-21          21       24       3       2019              4
377 2019-01-25        2876        1       1       2019              1
594 2019-04-14         547        4      86       2019              4
114 2019-11-28        6534       14       2       2019             11

In [18]:
date['date_month_name'] = date['date'].dt.month_name()

In [19]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
999,2019-10-15,6371,7,22,2019,10,October
51,2019-08-12,6344,26,1,2019,8,August
265,2019-04-28,2850,16,6,2019,4,April
535,2019-10-26,7318,25,1,2019,10,October
357,2019-02-09,532,18,1,2019,2,February

In [22]:
date['date_day'] = date['date'].dt.day

In [23]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
949,2019-01-01,6533,17,5,2019,1,January,1
727,2019-10-20,1932,18,6,2019,10,October,20
834,2018-07-27,398,22,8,2018,7,July,27
229,2019-11-29,4047,16,5,2019,11,November,29
232,2019-01-08,666,23,9,2019,1,January,8

In [24]:
date['date_dayofweek'] = date['date'].dt.dayofweek

In [25]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayofweek
422,2019-11-24,6717,3,1,2019,11,November,24,6
470,2019-11-22,3125,1,69,2019,11,November,22,4
115,2018-10-13,5779,13,6,2018,10,October,13,5
148,2019-12-10,561,13,1,2019,12,December,10,1
985,2018-12-08,5486,14,1,2018,12,December,8,5

In [28]:
date['date_name'] = date['date'].dt.day_name()

In [29]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayofweek,date_name
393,2019-05-19,2271,3,28,2019,5,May,19,6,Sunday
909,2018-10-10,3965,9,1,2018,10,October,10,2,Wednesday
894,2019-07-10,1533,18,82,2019,7,July,10,2,Wednesday
500,2019-07-25,5371,22,15,2019,7,July,25,3,Thursday
230,2018-07-22,7554,13,12,2018,7,July,22,6,Sunday

In [36]:
date['date_week'] = date['date'].dt.isocalendar().week

In [37]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayofweek,date_name,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1
...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0,Monday,41
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,49
997,2019-05-07,487,26,14,2019,5,May,7,1,Tuesday,19
998,2019-03-03,1503,21,2,2019,3,March,3,6,Sunday,9
999,2019-10-15,6371,7,22,2019,10,October,15,1,Tuesday,42

In [38]:
date['date_quarter'] = date['date'].dt.quarter

In [39]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dayofweek,date_name,date_week,date_quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0,Monday,41,4
996,2018-12-06,5521,7,1,2018,12,December,6,3,Thursday,49,4
997,2019-05-07,487,26,14,2019,5,May,7,1,Tuesday,19,2
998,2019-03-03,1503,21,2,2019,3,March,3,6,Sunday,9,1
999,2019-10-15,6371,7,22,2019,10,October,15,1,Tuesday,42,4